-- TippRadar – Supabase adatbázis
-- Ezt a teljes fájlt másold be a Supabase SQL Editorba, majd Run/Futtatás.

create table if not exists public.app_cache (
  cache_key text primary key,
  payload jsonb not null default '{}'::jsonb,
  expires_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.picks (
  id bigint generated by default as identity primary key,
  fixture_id bigint not null,
  pick_date date not null,
  league text,
  country text,
  home_team text not null,
  away_team text not null,
  kickoff timestamptz,
  recommendation text,
  market text,
  probability numeric(6,2),
  fair_odds numeric(8,2),
  market_odds numeric(8,2),
  edge numeric(8,2),
  rating text check (rating in ('green','yellow','red')),
  probabilities jsonb not null default '{}'::jsonb,
  injuries jsonb not null default '{}'::jsonb,
  api_advice text,
  coverage text,
  reasons jsonb not null default '[]'::jsonb,
  settled boolean not null default false,
  won boolean,
  home_score integer,
  away_score integer,
  unit_profit numeric(10,4),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (fixture_id, pick_date)
);

create index if not exists picks_pick_date_idx on public.picks (pick_date desc);
create index if not exists picks_rating_idx on public.picks (rating);
create index if not exists picks_settled_idx on public.picks (settled);

-- A böngésző SOHA nem kap Supabase titkos kulcsot.
-- Minden adatbázis-művelet a Netlify Functions szerveroldaláról történik.
alter table public.app_cache enable row level security;
alter table public.picks enable row level security;

-- Nem hozunk létre anon/authenticated policy-t. Így a publikus kliens nem tudja
-- közvetlenül olvasni vagy írni ezeket a táblákat. A szerveroldali Secret / service_role
-- kulcs BYPASSRLS jogosultsággal éri el őket.
