set lock_timeout = '10s';

alter table if exists public.picks
  add column if not exists model_version text not null default 'legacy',
  add column if not exists model_family text,
  add column if not exists data_quality numeric(5,2),
  add column if not exists market_period text not null default 'full',
  add column if not exists evidence jsonb not null default '{}'::jsonb,
  add column if not exists settled_at timestamptz,
  add column if not exists settlement_source text,
  add column if not exists brier_score numeric(10,8);

create index if not exists picks_model_version_idx on public.picks (model_version);
create index if not exists picks_settled_model_idx on public.picks (settled, model_version, pick_date desc);

create table if not exists public.model_runs (
  run_id text primary key,
  model_version text not null,
  sport text not null,
  run_date date not null,
  generated_at timestamptz not null default now(),
  total_events integer not null default 0,
  eligible_events integer not null default 0,
  picks_count integer not null default 0,
  green_count integer not null default 0,
  yellow_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists model_runs_date_idx on public.model_runs (run_date desc, sport);

create table if not exists public.settlement_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  lookback_days integer not null,
  pending_count integer not null default 0,
  settled_count integer not null default 0,
  error_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.analysis_locks (
  lock_key text primary key,
  owner_id text not null,
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create or replace function public.claim_analysis_lock(p_lock_key text, p_owner_id text, p_ttl_seconds integer default 90)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare claimed boolean := false;
begin
  insert into public.analysis_locks(lock_key, owner_id, expires_at, updated_at)
  values (p_lock_key, p_owner_id, now() + make_interval(secs => greatest(15, least(300, p_ttl_seconds))), now())
  on conflict (lock_key) do update
    set owner_id = excluded.owner_id,
        expires_at = excluded.expires_at,
        updated_at = now()
    where public.analysis_locks.expires_at < now()
  returning true into claimed;
  return coalesce(claimed, false);
end;
$$;

create or replace function public.release_analysis_lock(p_lock_key text, p_owner_id text)
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.analysis_locks where lock_key = p_lock_key and owner_id = p_owner_id;
$$;

create or replace view public.model_calibration
with (security_invoker = true)
as
select
  model_version,
  coalesce(substring(api_advice from '\[sport:([a-z0-9-]+)\]'), 'football') as sport,
  least(90, floor(probability / 10) * 10)::integer as probability_bucket,
  count(*)::integer as sample_size,
  round(avg(probability), 2) as average_prediction,
  round(avg(case when won then 100.0 else 0.0 end), 2) as observed_win_rate,
  round(avg(brier_score), 6) as average_brier_score
from public.picks
where settled = true and won is not null and probability is not null
group by model_version, sport, probability_bucket;

alter table public.model_runs enable row level security;
alter table public.settlement_runs enable row level security;
alter table public.analysis_locks enable row level security;

revoke all on public.model_runs, public.settlement_runs, public.analysis_locks from anon, authenticated;
revoke all on public.model_calibration from anon, authenticated;
revoke all on function public.claim_analysis_lock(text, text, integer) from public, anon, authenticated;
revoke all on function public.release_analysis_lock(text, text) from public, anon, authenticated;

grant all on public.model_runs, public.settlement_runs, public.analysis_locks to service_role;
grant select on public.model_calibration to service_role;
grant execute on function public.claim_analysis_lock(text, text, integer) to service_role;
grant execute on function public.release_analysis_lock(text, text) to service_role;
